// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://debekrkmwufjbjbxmyyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlYmVrcmttd3VmamJqYnhteXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzU4MTYsImV4cCI6MjA2MDUxMTgxNn0.QJeufaXAsqmdlFJg0O1_tbnXCV3j_dABueIBr5RET6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);